"""add phone number

Revision ID: 8f9f01d06d88
Revises: 0d2507fe68ff
Create Date: 2023-10-07 18:59:31.166805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9f01d06d88'
down_revision: Union[str, None] = '0d2507fe68ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('posts', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True,
    #            existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable= True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True,
    #            existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    # op.alter_column('posts', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
